services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - EMAIL_USE_TLS=0
    depends_on:
      - redis
      - mailhog
    stdin_open: true
    tty: true

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  celery:
    build: .
    command: celery -A carhub worker --loglevel=info
    env_file: .env
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - EMAIL_USE_TLS=0
    depends_on:
      - redis
      - mailhog
      - web

  celery-beat:
    build: .
    command: celery -A carhub beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file: .env
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - EMAIL_USE_TLS=0
    depends_on:
      - redis
      - mailhog
      - web
      - celery
