# Generated by Django 6.0.1 on 2026-01-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/%Y/%m/%d/', verbose_name='Главное фото'),
        ),
        migrations.AddField(
            model_name='historicalcar',
            name='main_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Главное фото'),
        ),
    ]
