# Generated by Django 6.0.1 on 2026-06-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_car_main_image_historicalcar_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Обычный пользователь'), ('seller', 'Продавец'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='seller', max_length=20, verbose_name='Роль'),
        ),
    ]
